webtalk_init -webtalk_dir C:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS/RFDC_DDS/RFDC_DDS.sim/sim_1/behav/xsim/xsim.dir/RFDC_DDS_TB00_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 29 14:26:29 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211846954_0_0_001" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a351b397-e8c3-4ae6-9202-8b12bfe092e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a9b6b66eff794337b4b2f870cdb7bc9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21992_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3391989013 -regid "211846954_0_0_001" -xml C:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS/RFDC_DDS/RFDC_DDS.sim/sim_1/behav/xsim/xsim.dir/RFDC_DDS_TB00_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS/RFDC_DDS/RFDC_DDS.sim/sim_1/behav/xsim/xsim.dir/RFDC_DDS_TB00_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS/RFDC_DDS/RFDC_DDS.sim/sim_1/behav/xsim/xsim.dir/RFDC_DDS_TB00_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
