@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 23 13:26:42 +0900 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TestBench00_behav -key {Behavioral:sim_1:Functional:TestBench00} -tclbatch TestBench00.tcl -protoinst "protoinst_files/RFSoC_Simple_block_01.protoinst" -log simulate.log"
call xsim  TestBench00_behav -key {Behavioral:sim_1:Functional:TestBench00} -tclbatch TestBench00.tcl -protoinst "protoinst_files/RFSoC_Simple_block_01.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
