# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.srcs/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0.xci
# IP: The module: 'TEST_02_Block_util_ds_buf_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_02_Block_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_02_Block_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.srcs/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0.xci
# IP: The module: 'TEST_02_Block_util_ds_buf_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_02_Block_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TEST_02_Block_util_ds_buf_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
