# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main/ZCU111_Rev1.0.xdc

# Block Designs: bd/RFSoC_Main_test_blk/RFSoC_Main_test_blk.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk || ORIG_REF_NAME==RFSoC_Main_test_blk} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/RFSoC_Main_test_blk_DAC_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_DAC_Controller_0_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_DAC_Controller_0_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_proc_sys_reset_0_0/RFSoC_Main_test_blk_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_proc_sys_reset_0_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_TimeController_0_0/RFSoC_Main_test_blk_TimeController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_TimeController_0_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_TimeController_0_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_xbar_0/RFSoC_Main_test_blk_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_xbar_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_xbar_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_auto_ds_0/RFSoC_Main_test_blk_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_auto_ds_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_auto_ds_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_auto_pc_0/RFSoC_Main_test_blk_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_auto_pc_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_auto_pc_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_axi_interconnect_0_0/RFSoC_Main_test_blk_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_axi_interconnect_0_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_usp_rf_data_converter_0_0/RFSoC_Main_test_blk_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_usp_rf_data_converter_0_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_zynq_ultra_ps_e_0_0/RFSoC_Main_test_blk_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RFSoC_Main_test_blk_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==RFSoC_Main_test_blk_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/RFSoC_Main_test_blk_ooc.xdc
