# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/dds_compiler_5/dds_compiler_5.xci
# IP: The module: 'dds_compiler_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/dds_compiler_5/dds_compiler_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/dds_compiler_5/dds_compiler_5.xci
# IP: The module: 'dds_compiler_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/dds_compiler_5/dds_compiler_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_compiler_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
