# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.srcs/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/TEST_02_Block_DAC_Controller_0_0.xci
# IP: The module: 'TEST_02_Block_DAC_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_3/fifo_generator_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_3 || ORIG_REF_NAME==fifo_generator_3} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_2/fifo_generator_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_2 || ORIG_REF_NAME==fifo_generator_2} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_1/fifo_generator_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_3/fifo_generator_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_3 || ORIG_REF_NAME==fifo_generator_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_2/fifo_generator_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_2 || ORIG_REF_NAME==fifo_generator_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_1/fifo_generator_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: E:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.srcs/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/TEST_02_Block_DAC_Controller_0_0.xci
# IP: The module: 'TEST_02_Block_DAC_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_3/fifo_generator_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_3 || ORIG_REF_NAME==fifo_generator_3} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_2/fifo_generator_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_2 || ORIG_REF_NAME==fifo_generator_2} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_1/fifo_generator_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_3/fifo_generator_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_3 || ORIG_REF_NAME==fifo_generator_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_2/fifo_generator_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_2 || ORIG_REF_NAME==fifo_generator_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_1/fifo_generator_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_04/TEST_02.gen/sources_1/bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
