# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.srcs/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_auto_pc_0/RFSoC_Main_blk_auto_pc_0.xci
# IP: The module: 'RFSoC_Main_blk_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_auto_pc_0/RFSoC_Main_blk_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFSoC_Main_blk_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.srcs/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_auto_pc_0/RFSoC_Main_blk_auto_pc_0.xci
# IP: The module: 'RFSoC_Main_blk_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_auto_pc_0/RFSoC_Main_blk_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RFSoC_Main_blk_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
