# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/ZCU111_Rev1.0.xdc

# Block Designs: bd/TEST_02_Block/TEST_02_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block || ORIG_REF_NAME==TEST_02_Block} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_zynq_ultra_ps_e_0_0/TEST_02_Block_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==TEST_02_Block_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_xbar_0/TEST_02_Block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_xbar_0 || ORIG_REF_NAME==TEST_02_Block_xbar_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_auto_ds_0/TEST_02_Block_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_auto_ds_0 || ORIG_REF_NAME==TEST_02_Block_auto_ds_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_auto_pc_0/TEST_02_Block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_auto_pc_0 || ORIG_REF_NAME==TEST_02_Block_auto_pc_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_axi_interconnect_0_0/TEST_02_Block_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_axi_interconnect_0_0 || ORIG_REF_NAME==TEST_02_Block_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_proc_sys_reset_0_0/TEST_02_Block_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_proc_sys_reset_0_0 || ORIG_REF_NAME==TEST_02_Block_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_DAC_Controller_0_0/TEST_02_Block_DAC_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_DAC_Controller_0_0 || ORIG_REF_NAME==TEST_02_Block_DAC_Controller_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_TimeController_0_0/TEST_02_Block_TimeController_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_TimeController_0_0 || ORIG_REF_NAME==TEST_02_Block_TimeController_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_usp_rf_data_converter_0_0/TEST_02_Block_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_usp_rf_data_converter_0_0 || ORIG_REF_NAME==TEST_02_Block_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_clk_wiz_0_1/TEST_02_Block_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_clk_wiz_0_1 || ORIG_REF_NAME==TEST_02_Block_clk_wiz_0_1} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_0_0/TEST_02_Block_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_util_ds_buf_0_0 || ORIG_REF_NAME==TEST_02_Block_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/TEST_02_Block/ip/TEST_02_Block_util_ds_buf_1_0/TEST_02_Block_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TEST_02_Block_util_ds_buf_1_0 || ORIG_REF_NAME==TEST_02_Block_util_ds_buf_1_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_RFDC_Test/IP_FILE_06/TEST_03/TEST_02.gen/sources_1/bd/TEST_02_Block/TEST_02_Block_ooc.xdc
