# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.srcs/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/RFSoC_Main_test_blk_DAC_Controller_0_0.xci
# IP: The module: 'RFSoC_Main_test_blk_DAC_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_15/dds_compiler_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_15 || ORIG_REF_NAME==dds_compiler_15} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_14/dds_compiler_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_14 || ORIG_REF_NAME==dds_compiler_14} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_13/dds_compiler_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_13 || ORIG_REF_NAME==dds_compiler_13} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_12/dds_compiler_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_12 || ORIG_REF_NAME==dds_compiler_12} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_11/dds_compiler_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_11 || ORIG_REF_NAME==dds_compiler_11} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_10/dds_compiler_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_10 || ORIG_REF_NAME==dds_compiler_10} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_9/dds_compiler_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_9 || ORIG_REF_NAME==dds_compiler_9} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_8/dds_compiler_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_8 || ORIG_REF_NAME==dds_compiler_8} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_7/dds_compiler_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_7 || ORIG_REF_NAME==dds_compiler_7} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_6/dds_compiler_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_6 || ORIG_REF_NAME==dds_compiler_6} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_5/dds_compiler_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_5 || ORIG_REF_NAME==dds_compiler_5} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_4/dds_compiler_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_4 || ORIG_REF_NAME==dds_compiler_4} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_3/dds_compiler_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_3 || ORIG_REF_NAME==dds_compiler_3} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_2/dds_compiler_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2 || ORIG_REF_NAME==dds_compiler_2} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_1/dds_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_0/dds_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.srcs/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/RFSoC_Main_test_blk_DAC_Controller_0_0.xci
# IP: The module: 'RFSoC_Main_test_blk_DAC_Controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_15/dds_compiler_15.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_15 || ORIG_REF_NAME==dds_compiler_15} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_14/dds_compiler_14.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_14 || ORIG_REF_NAME==dds_compiler_14} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_13/dds_compiler_13.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_13 || ORIG_REF_NAME==dds_compiler_13} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_12/dds_compiler_12.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_12 || ORIG_REF_NAME==dds_compiler_12} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_11/dds_compiler_11.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_11 || ORIG_REF_NAME==dds_compiler_11} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_10/dds_compiler_10.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_10 || ORIG_REF_NAME==dds_compiler_10} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_9/dds_compiler_9.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_9 || ORIG_REF_NAME==dds_compiler_9} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_8/dds_compiler_8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_8 || ORIG_REF_NAME==dds_compiler_8} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_7/dds_compiler_7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_7 || ORIG_REF_NAME==dds_compiler_7} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_6/dds_compiler_6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_6 || ORIG_REF_NAME==dds_compiler_6} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_5/dds_compiler_5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_5 || ORIG_REF_NAME==dds_compiler_5} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_4/dds_compiler_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_4 || ORIG_REF_NAME==dds_compiler_4} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_3/dds_compiler_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_3 || ORIG_REF_NAME==dds_compiler_3} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_2/dds_compiler_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_2 || ORIG_REF_NAME==dds_compiler_2} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_1/dds_compiler_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_1 || ORIG_REF_NAME==dds_compiler_1} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/dds_compiler_0/dds_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFSoC_Main_test/RFSoC_Main_test/RFSoC_Main_test.gen/sources_1/bd/RFSoC_Main_test_blk/ip/RFSoC_Main_test_blk_DAC_Controller_0_0/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
