# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.srcs/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/RFSoC_Main_blk_DAC_Controller_1_0.xci
# IP: The module: 'RFSoC_Main_blk_DAC_Controller_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_15/dac_controller_dds_1_compiler_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_15 || ORIG_REF_NAME==dac_controller_dds_1_compiler_15} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_14/dac_controller_dds_1_compiler_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_14 || ORIG_REF_NAME==dac_controller_dds_1_compiler_14} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_13/dac_controller_dds_1_compiler_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_13 || ORIG_REF_NAME==dac_controller_dds_1_compiler_13} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_12/dac_controller_dds_1_compiler_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_12 || ORIG_REF_NAME==dac_controller_dds_1_compiler_12} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_11/dac_controller_dds_1_compiler_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_11 || ORIG_REF_NAME==dac_controller_dds_1_compiler_11} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_10/dac_controller_dds_1_compiler_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_10 || ORIG_REF_NAME==dac_controller_dds_1_compiler_10} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_9/dac_controller_dds_1_compiler_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_9 || ORIG_REF_NAME==dac_controller_dds_1_compiler_9} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_8/dac_controller_dds_1_compiler_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_8 || ORIG_REF_NAME==dac_controller_dds_1_compiler_8} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_7/dac_controller_dds_1_compiler_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_7 || ORIG_REF_NAME==dac_controller_dds_1_compiler_7} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_6/dac_controller_dds_1_compiler_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_6 || ORIG_REF_NAME==dac_controller_dds_1_compiler_6} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_5/dac_controller_dds_1_compiler_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_5 || ORIG_REF_NAME==dac_controller_dds_1_compiler_5} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_4/dac_controller_dds_1_compiler_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_4 || ORIG_REF_NAME==dac_controller_dds_1_compiler_4} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_3/dac_controller_dds_1_compiler_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_3 || ORIG_REF_NAME==dac_controller_dds_1_compiler_3} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_2/dac_controller_dds_1_compiler_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_2 || ORIG_REF_NAME==dac_controller_dds_1_compiler_2} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_1/dac_controller_dds_1_compiler_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_1 || ORIG_REF_NAME==dac_controller_dds_1_compiler_1} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_0/dac_controller_dds_1_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_0 || ORIG_REF_NAME==dac_controller_dds_1_compiler_0} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_fifo_1_generator_0/dac_controller_fifo_1_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_fifo_1_generator_0 || ORIG_REF_NAME==dac_controller_fifo_1_generator_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_fifo_1_generator_0/dac_controller_fifo_1_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==dac_controller_fifo_1_generator_0 || ORIG_REF_NAME==dac_controller_fifo_1_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.srcs/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/RFSoC_Main_blk_DAC_Controller_1_0.xci
# IP: The module: 'RFSoC_Main_blk_DAC_Controller_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_15/dac_controller_dds_1_compiler_15.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_15 || ORIG_REF_NAME==dac_controller_dds_1_compiler_15} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_14/dac_controller_dds_1_compiler_14.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_14 || ORIG_REF_NAME==dac_controller_dds_1_compiler_14} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_13/dac_controller_dds_1_compiler_13.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_13 || ORIG_REF_NAME==dac_controller_dds_1_compiler_13} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_12/dac_controller_dds_1_compiler_12.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_12 || ORIG_REF_NAME==dac_controller_dds_1_compiler_12} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_11/dac_controller_dds_1_compiler_11.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_11 || ORIG_REF_NAME==dac_controller_dds_1_compiler_11} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_10/dac_controller_dds_1_compiler_10.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_10 || ORIG_REF_NAME==dac_controller_dds_1_compiler_10} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_9/dac_controller_dds_1_compiler_9.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_9 || ORIG_REF_NAME==dac_controller_dds_1_compiler_9} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_8/dac_controller_dds_1_compiler_8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_8 || ORIG_REF_NAME==dac_controller_dds_1_compiler_8} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_7/dac_controller_dds_1_compiler_7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_7 || ORIG_REF_NAME==dac_controller_dds_1_compiler_7} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_6/dac_controller_dds_1_compiler_6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_6 || ORIG_REF_NAME==dac_controller_dds_1_compiler_6} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_5/dac_controller_dds_1_compiler_5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_5 || ORIG_REF_NAME==dac_controller_dds_1_compiler_5} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_4/dac_controller_dds_1_compiler_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_4 || ORIG_REF_NAME==dac_controller_dds_1_compiler_4} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_3/dac_controller_dds_1_compiler_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_3 || ORIG_REF_NAME==dac_controller_dds_1_compiler_3} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_2/dac_controller_dds_1_compiler_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_2 || ORIG_REF_NAME==dac_controller_dds_1_compiler_2} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_1/dac_controller_dds_1_compiler_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_1 || ORIG_REF_NAME==dac_controller_dds_1_compiler_1} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_dds_1_compiler_0/dac_controller_dds_1_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_dds_1_compiler_0 || ORIG_REF_NAME==dac_controller_dds_1_compiler_0} -quiet] -quiet

# IP: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_fifo_1_generator_0/dac_controller_fifo_1_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dac_controller_fifo_1_generator_0 || ORIG_REF_NAME==dac_controller_fifo_1_generator_0} -quiet] -quiet

# XDC: e:/RFSoC/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_01/RFSoC_Main_output/RFSoC_Main/RFSoC_Main.gen/sources_1/bd/RFSoC_Main_blk/ip/RFSoC_Main_blk_DAC_Controller_1_0/dac_controller_fifo_1_generator_0/dac_controller_fifo_1_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==dac_controller_fifo_1_generator_0 || ORIG_REF_NAME==dac_controller_fifo_1_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
