# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.srcs/sources_1/ip/usp_rf_data_converter_0/usp_rf_data_converter_0.xci
# IP: The module: 'usp_rf_data_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.gen/sources_1/ip/usp_rf_data_converter_0/synth/usp_rf_data_converter_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'usp_rf_data_converter_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.gen/sources_1/ip/usp_rf_data_converter_0/synth/usp_rf_data_converter_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'usp_rf_data_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.gen/sources_1/ip/usp_rf_data_converter_0/synth/usp_rf_data_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'usp_rf_data_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.srcs/sources_1/ip/usp_rf_data_converter_0/usp_rf_data_converter_0.xci
# IP: The module: 'usp_rf_data_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.gen/sources_1/ip/usp_rf_data_converter_0/synth/usp_rf_data_converter_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'usp_rf_data_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.gen/sources_1/ip/usp_rf_data_converter_0/synth/usp_rf_data_converter_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'usp_rf_data_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Jeonghyun/GIT/RFSoC/RFSoC_Design_V1_1/IP_File_00/RFDC_DDS_test/RFDC_DDS_test/RFDC_DDS_test.gen/sources_1/ip/usp_rf_data_converter_0/synth/usp_rf_data_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'usp_rf_data_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
